[program:redis]
command=/usr/bin/redis-server /etc/redis/redis.conf --daemonize no
priority=9
directory=/
autostart=true
autorestart=true
startretries=10
stopsignal=TERM
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/supervisor/%(program_name)s_stderr.log
stderr_logfile_maxbytes=10MB
stdout_logfile=/var/log/supervisor/%(program_name)s_stdout.log
stdout_logfile_maxbytes=10MB
redirect_stderr=true
