auth_request /_auth;
auth_request_set $auth_status $upstream_status;

auth_request_set $auth_user  $upstream_http_x_auth_user;
auth_request_set $auth_email $upstream_http_x_auth_email;
auth_request_set $auth_roles $upstream_http_x_auth_roles;
auth_request_set $auth_realm $upstream_http_x_auth_realm;

proxy_set_header X-Auth-User  $auth_user;
proxy_set_header X-Auth-Email $auth_email;
# proxy_set_header X-Auth-Roles $auth_roles;
# proxy_set_header X-Auth-Realm $auth_realm;